# Installing Numpy and Numpy Array Creation 

In [1]:
#install pip pakage in the Jupyter Kernel
! Pip install Numpy

In [2]:
lst=[1,2,3,4,5,6,7]
print(type(lst))
print("list:", lst)

<class 'list'>
list: [1, 2, 3, 4, 5, 6, 7]


In [4]:
import numpy as np 
arr=np.array(lst)
print(type(arr))
print("Numpy array:", arr)

<class 'numpy.ndarray'>
Numpy array: [1 2 3 4 5 6 7]


In [5]:
#creating a simple array in numpy using np.arange

arr=np.arange(10)
print(type(arr))
print("Numpy Array:", arr)

<class 'numpy.ndarray'>
Numpy Array: [0 1 2 3 4 5 6 7 8 9]


# Why Numpy?
>Most powerful numerical processing library in python. Array Oriented computing.
>Provides extension package to python for multi dimensional array.
>Very efficient.
>Scientific computation.

# But why Numpy when we already have a list?

In [6]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

CPU times: total: 562 ms
Wall time: 573 ms


In [7]:
%%time

arr = np.arange(1000000)

arr = arr * arr


CPU times: total: 0 ns
Wall time: 11.1 ms


# Numpy Array and It's Attributes/Properties


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array :\n",arr)

#print shape
print("shape:",arr.shape)

#print datatype
print("Data Type:",arr.dtype)

#print item size in byte of each element
print("Item size",arr.itemsize)

#print the dimensionality of the numpy array
print("Dimensionality:",arr.ndim)


Array :
 [1 2 3 4 5]
shape: (5,)
Data Type: int32
Item size 4
Dimensionality: 1


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)

#print shape
print("shape:",arr.shape)

#print Data Type
print("Data Type:",arr.dtype)

#print Item size
print("Item Size:",arr.itemsize)

#print dimensionlaity of the numpy array
print("Dimmensionality:",arr.ndim)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Data Type: int32
Item Size: 4
Dimmensionality: 2


# Functions for creating Numpy Array

In [27]:
arr = np.arange(10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape:  (10,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [29]:
arr = np.arange(1, 10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [30]:
arr = np.arange(1, 10, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 3 5 7 9]
Shape:  (5,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [31]:
arr = np.ones((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [32]:
arr = np.zeros((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [33]:
arr = np.eye(3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [34]:
arr = np.eye(3, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape:  (3, 2)
Data Type:  float64
Item Size:  8
Dimensionality:  2


# Datatypes in Numpy
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
str - string
f - float
m - timedelta
M - datetime
O - object
u - unsigned integer
c - complex float
U - unicode string
V - fixed chunk of memory for other type ( void )

In [35]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='f')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)


Array: 
 [2. 1. 4. 5.]
Data Type:  float32


In [36]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='O')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


In [37]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='str')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 ['2' '1' '4' '5']
Data Type:  <U1


# Numpy Random Numbers
>np.random.rand - generates an array with random numbers that are uniformly distribute between 0 and 1.
np.random.randn - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
np.random.randint - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
np.random.uniform - generates an array with random numbers (float) between given numbers.

In [38]:
# Randomly generate an array from uniform distribution
import numpy as np

arr = np.random.rand(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [0.86580513 0.18889015 0.08962988 0.72266382 0.41534193]


In [39]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)

print("Numpy Array generated randomly from uniform distribution: \n", arr)

Numpy Array generated randomly from uniform distribution: 
 [[0.22907978 0.51061541]
 [0.41011852 0.11377698]
 [0.5513418  0.49905655]
 [0.63263626 0.25189981]
 [0.47084314 0.17857277]
 [0.16882801 0.81233475]
 [0.10527324 0.27572979]
 [0.85476771 0.76357379]
 [0.88316409 0.90332687]
 [0.48099913 0.86256103]]


In [40]:
# Randomly generate an array from normal distribution
import numpy as np

arr = np.random.randn(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [ 0.25014861  0.71538865 -0.42380749 -1.61138093  0.2910965 ]


In [41]:
# Randomly generate an array with 5 rows and 4 columns
arr = np.random.randn(5, 4)

print("Numpy Array generated randomly from normal distribution: \n", arr)

Numpy Array generated randomly from normal distribution: 
 [[ 0.29371526 -0.93230419  0.88675337  0.91395489]
 [-1.09104721 -0.45789225 -0.621473    0.70183051]
 [ 0.45443104 -0.46260891 -0.01971763 -0.06017508]
 [ 0.46608443 -1.16095591  1.18647319 -0.85223438]
 [-0.96539189  0.43694387  0.49676105  0.20551792]]


In [42]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

7


In [43]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[9 2 6 7]
 [1 3 0 1]
 [7 9 1 1]
 [2 7 6 0]
 [6 9 8 6]]


In [44]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[34 11 25 36 38 34 36 36 20 16]
 [24 18 18 14 16 31 15 29 16 13]
 [17 25 34 32 31 12 24 34 25 24]
 [12 18 19 13 23 30 36 14 35 31]
 [16 17 23 17 24 30 27 24 21 33]]


In [45]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)

print(value)

3.720691564965149


In [46]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)


Numpy Array: 
 [[8.64827323 2.11621408 3.79720158 6.17749297]
 [5.93385352 7.59461169 9.40078781 8.24676944]
 [3.01617407 3.24825425 8.80057517 9.2132629 ]
 [9.26301767 6.3304767  2.56883991 7.60601603]
 [3.15234017 5.92799701 7.38582749 3.99186141]]


In [47]:
# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[23.60918814 36.42603056 13.71037073]
 [24.17017558 14.08870687 17.32964148]
 [33.91267998 10.96356474 26.15981742]
 [14.29471533 10.45320123 15.69393904]
 [38.47952148 27.23053314 13.04616956]]


# Numpy Array - Indexing, Slicing and Updating 
>Since data in numpy array is stored sequentially, it is possible to access the data with the help of Indexing and Slicing operation. NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

>Also remember that numpy array's are mutable. i.e. Data stored in numpy array can be updated/changed.

In [48]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [53 85 47 52 59]
Shape:  (5,)


In [49]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  47


In [50]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[58 45 98 32]
 [48 97 81 23]
 [87 17  5 94]
 [91 11 62 22]
 [90 81 64 48]]


In [51]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  [87 17  5 94]


In [52]:
# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Accessing Value using Way-1:  17
Accessing Value using Way-2:  17


In [53]:
# Accesssing multiple values
print(arr[[2, 1], [1, 1]])

[17 97]


# Data Accessing using Slicing in Numpy Array 

In [54]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [62  1 95 58 90 82 90 59 43 40]
Shape:  (10,)


In [55]:
print(arr[1:4])

print(arr[0:-4])

print(arr[::2])

[ 1 95 58]
[62  1 95 58 90 82]
[62 95 90 90 43]


In [56]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)


In [58]:
# # Remember Way-2 for accessing the data in Numpy array
print(arr[:2, 1:3])

[[2 3]
 [6 7]]


In [59]:
print(arr[1:2, :])

[[5 6 7 8]]


# Indexing with Boolean Arrays

In [60]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [21 72 21 31  5 87 79 48 59 79]
Shape:  (10,)


In [61]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[21 87 59 79]


# Updating Data in Numpy Array


In [62]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[70 22 93 94]
 [38 92 76 89]
 [91 94 33  1]
 [ 2 55 89 44]
 [88 17 27  2]]
Updated Array: 
 [[70 22 93 94]
 [38 99 76 89]
 [91 94 33  1]
 [ 2 55 89 44]
 [88 17 27  2]]


# Numpy Flatten and Ravel

In [63]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[37 37 33 33 20 12 21 39 31 23]
 [10 38 20 38 15 34 22 23 15 26]
 [21 34 32 32 24 22 37 39 35 33]
 [18 37 16 23 33 32 11 30 26 30]
 [31 36 31 34 39 11 19 15 32 14]]
Shape:  (5, 10)


In [64]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [37 37 33 33 20 12 21 39 31 23 10 38 20 38 15 34 22 23 15 26 21 34 32 32
 24 22 37 39 35 33 18 37 16 23 33 32 11 30 26 30 31 36 31 34 39 11 19 15
 32 14]
Shape:  (50,)


In [65]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [37 37 33 33 20 12 21 39 31 23 10 38 20 38 15 34 22 23 15 26 21 34 32 32
 24 22 37 39 35 33 18 37 16 23 33 32 11 30 26 30 31 36 31 34 39 11 19 15
 32 14]
Shape:  (50,)


# Look's like both are performing fatten operation on the array data. But is there any difference between two functions?

In [66]:
# Updating value in the array
print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[37 37 33 33 20 12 21 39 31 23]
 [10 38 20 38 15 34 22 23 15 26]
 [21 34 32 32 24 22 37 39 35 33]
 [18 37 16 23 33 32 11 30 26 30]
 [31 36 31 34 39 11 19 15 32 14]]
Updated Array: 
 [[37 37 33 33 20 12 21 39 31 23]
 [10 99 20 38 15 34 22 23 15 26]
 [21 34 32 32 24 22 37 39 35 33]
 [18 37 16 23 33 32 11 30 26 30]
 [31 36 31 34 39 11 19 15 32 14]]


In [67]:
print("Flatten Array: \n", flatten_arr)

print("Ravel Array: \n", ravel_arr)

Flatten Array: 
 [37 37 33 33 20 12 21 39 31 23 10 38 20 38 15 34 22 23 15 26 21 34 32 32
 24 22 37 39 35 33 18 37 16 23 33 32 11 30 26 30 31 36 31 34 39 11 19 15
 32 14]
Ravel Array: 
 [37 37 33 33 20 12 21 39 31 23 10 99 20 38 15 34 22 23 15 26 21 34 32 32
 24 22 37 39 35 33 18 37 16 23 33 32 11 30 26 30 31 36 31 34 39 11 19 15
 32 14]


# Observation
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

# Numpy Reshape

In [68]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[10 34 21 19 27 24 11 34 39 20]
 [25 18 27 34 18 22 17 18 13 15]
 [26 29 35 10 19 34 35 21 33 21]
 [24 27 14 32 15 33 37 13 39 30]
 [28 21 14 16 29 30 16 16 35 18]]
Shape:  (5, 10)


In [69]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[10 34 21 19 27]
 [24 11 34 39 20]
 [25 18 27 34 18]
 [22 17 18 13 15]
 [26 29 35 10 19]
 [34 35 21 33 21]
 [24 27 14 32 15]
 [33 37 13 39 30]
 [28 21 14 16 29]
 [30 16 16 35 18]]


In [70]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[10 34]
 [21 19]
 [27 24]
 [11 34]
 [39 20]
 [25 18]
 [27 34]
 [18 22]
 [17 18]
 [13 15]
 [26 29]
 [35 10]
 [19 34]
 [35 21]
 [33 21]
 [24 27]
 [14 32]
 [15 33]
 [37 13]
 [39 30]
 [28 21]
 [14 16]
 [29 30]
 [16 16]
 [35 18]]


# Iterating over Numpy Array

Iterating Over one Dimensional Array

In [75]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [36 26 33 23 37 26 25 15 19 39]
Shape:  (10,)


In [76]:
# Looping over items in the array
for item in arr1d:
    print(item, end=" ")

36 26 33 23 37 26 25 15 19 39 

## Iterating over a 2 Dimensional Array

In [78]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr2d = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr2d)

print("Shape: ", arr2d.shape)

Numpy Array: 
 [[27 32 19 32 30 32 38 26 33 35]
 [13 29 13 31 15 16 32 28 16 10]
 [20 38 12 36 26 20 38 14 38 20]
 [30 10 25 30 32 15 31 11 12 30]
 [24 24 11 34 32 37 10 21 17 20]]
Shape:  (5, 10)


In [79]:
# Looping over rows in the 2d array
for row in arr2d:
    print(row)

[27 32 19 32 30 32 38 26 33 35]
[13 29 13 31 15 16 32 28 16 10]
[20 38 12 36 26 20 38 14 38 20]
[30 10 25 30 32 15 31 11 12 30]
[24 24 11 34 32 37 10 21 17 20]


In [80]:
# Looping over each item in the 2d array
for item in arr2d.ravel():
    print(item, end=" ")

27 32 19 32 30 32 38 26 33 35 13 29 13 31 15 16 32 28 16 10 20 38 12 36 26 20 38 14 38 20 30 10 25 30 32 15 31 11 12 30 24 24 11 34 32 37 10 21 17 20 

## Iterating using np.nditer()

In [81]:
for item in np.nditer(arr1d):
    print(item, end=' ')

36 26 33 23 37 26 25 15 19 39 

In [82]:
for item in np.nditer(arr2d):
    print(item, end=' ')

27 32 19 32 30 32 38 26 33 35 13 29 13 31 15 16 32 28 16 10 20 38 12 36 26 20 38 14 38 20 30 10 25 30 32 15 31 11 12 30 24 24 11 34 32 37 10 21 17 20 

In [83]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d, op_flags=['readwrite']):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [36 26 33 23 37 26 25 15 19 39]
Updated Array [ 0  0  0  0  0  0  0 15 19  0]


## Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Using a Loop)

In [84]:
import numpy as np

# Step 1: Generate a 5x4 array with random positive integers (let's use values between 1 and 100)
array = np.random.randint(1, 101, size=(5, 4))
print("Original Array:")
print(array)

# Step 2: Replace all odd numbers with -1 using a loop
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if array[i, j] % 2 != 0:  # Check if the number is odd
            array[i, j] = -1

print("\nUpdated Array (odd numbers replaced by -1):")
print(array)


Original Array:
[[63 95 85 71]
 [86 22 68  5]
 [61 36  5 49]
 [12 49 86 81]
 [62 63 81 21]]

Updated Array (odd numbers replaced by -1):
[[-1 -1 -1 -1]
 [86 22 68 -1]
 [-1 36 -1 -1]
 [12 -1 86 -1]
 [62 -1 -1 -1]]


# #Python Operators on Numpy Array

In [85]:
# We can apply any python operator on Numpy Array.
# It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [86]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [87]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [88]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [89]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


## Exercise: Write a program to filter the values from the array based on below mentioned conditions:
Either value should be divisible by 5.
(or) value should be an odd number and factor of 7.

In [90]:
import numpy as np

# Original array
arr = np.array([10, 14, 35, 49, 7, 25, 28, 20, 21])

# Condition 1: Values divisible by 5
div_by_5 = arr % 5 == 0

# Condition 2: Odd numbers and factor of 7
odd_and_factor_of_7 = (arr % 2 != 0) & (arr % 7 == 0)

# Applying the conditions
filtered_arr = arr[div_by_5 | odd_and_factor_of_7]

print(filtered_arr)


[10 35 49  7 25 20 21]


# Numpy Maths

In [91]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [92]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [93]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [94]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


In [95]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [96]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


# Numpy Statistics

In [97]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise

print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [98]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise

print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [99]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [100]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

# Miscellaneous Topics


## Linspace

In [101]:
# Syntax => np.linspace(begin, end, # of elements)

print(np.linspace(1, 5, 9))


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [102]:
print(np.linspace(10, 13, 6))

[10.  10.6 11.2 11.8 12.4 13. ]


## Sorting

In [103]:
import numpy as np

arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[76 80 96 64 86 85 64 61 79 78]
 [50 61 78 68 64 64 94 73 99 51]
 [50 55 90 59 70 53 83 65 57 87]
 [69 76 58 64 69 90 87 92 93 72]
 [83 93 54 97 88 78 85 84 73 70]]


In [104]:
np.sort(arr)

array([[61, 64, 64, 76, 78, 79, 80, 85, 86, 96],
       [50, 51, 61, 64, 64, 68, 73, 78, 94, 99],
       [50, 53, 55, 57, 59, 65, 70, 83, 87, 90],
       [58, 64, 69, 69, 72, 76, 87, 90, 92, 93],
       [54, 70, 73, 78, 83, 84, 85, 88, 93, 97]])

In [105]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[50, 55, 54, 59, 64, 53, 64, 61, 57, 51],
       [50, 61, 58, 64, 69, 64, 83, 65, 73, 70],
       [69, 76, 78, 64, 70, 78, 85, 73, 79, 72],
       [76, 80, 90, 68, 86, 85, 87, 84, 93, 78],
       [83, 93, 96, 97, 88, 90, 94, 92, 99, 87]])

In [106]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[61, 64, 64, 76, 78, 79, 80, 85, 86, 96],
       [50, 51, 61, 64, 64, 68, 73, 78, 94, 99],
       [50, 53, 55, 57, 59, 65, 70, 83, 87, 90],
       [58, 64, 69, 69, 72, 76, 87, 90, 92, 93],
       [54, 70, 73, 78, 83, 84, 85, 88, 93, 97]])

## Stacking

In [107]:
arr_1 = np.arange(5,15).reshape(2,5)

print(arr_1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [108]:
arr_2 = np.arange(25,35).reshape(2,5)
print(arr_2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [109]:
np.vstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [110]:
np.hstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

## Concatenate

In [111]:
np.concatenate([arr_1, arr_2], axis = 0) # concatinating - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [112]:
np.concatenate([arr_1, arr_2], axis = 1) # concatinating - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

## Append

In [113]:
np.append(arr_1, arr_2, axis = 0) # Appending - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [114]:
np.append(arr_1, arr_2, axis = 1) # Appending - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

## Where - Process Array Elements Conditionally
Understanding np.where() Syntax

numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)

In [115]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [116]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [117]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

# argsort

In [118]:
import numpy as np

arr = np.array([10, -5, 6, -1])

print("Indexes: ", arr.argsort()) # Returns indexes

print("Sorted Array: ", arr[arr.argsort()])

Indexes:  [1 3 2 0]
Sorted Array:  [-5 -1  6 10]


## Numpy Broadcasting
Start matching the dimensions backward (Right to Left)
Compatible - If same number appears or if one of them is 1
Incompatible - Otherwise

In [119]:
import numpy as np


In [120]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [121]:
##Run this program

arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([[1], [2]])

print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]
